### PR TITLE
Add direction:ltr as the plugin breaks on rtl layout

### PR DESCRIPTION
**Pull request by felixmosh**
The plugin breaks on RTL layouts (all the calculations becomes incorrect).

Related to #66

### CODE REVIEW

**Comment by felixmosh** [comment]
BTW, I've managed to add some support for RTL in the plugin, it works with a swipe & nav buttons...
ZDv31gCXBj

But probably not covers all the use-cases, would you like to collaborate on a PR for full support?

**Comment by maxmarinich** [comment]
@felixmosh, could you provide code sample like [here](https://codesandbox.io/s/zrlmr3p61m)?

**Comment by felixmosh** [comment]
I've uploaded my version, 
https://github.com/felixmosh/react-alice-carousel/tree/prod-version

**Pay attention** that I've striped some unused functionality to reduce bundle size.
https://codesandbox.io/s/react-alice-carousel-rtl-207jd

**Comment by felixmosh** [comment]
@maxmarinich did you had a chance to look at my fix?

**Comment by maxmarinich** [comment]
Hi, Felix! Please, create PR for this.

вс, 8 дек. 2019 г. в 10:56, Felix Mosheev <notifications@github.com>:

**Pull request merged**
