### PR TITLE
Full RTL support

### PR DESCRIPTION
**Pull request by felixmosh**
This PR adds full RTL mode, based on flex layout and negative calculations.

ZDv31gCXBj

### CODE REVIEW

**Comment by maxmarinich** [comment]
Hi, @felixmosh! Thanks for the PR. But the code is buggy a little and not fully consider rtl flow. The full rtl support will include in v2. 
If you have intention update the current version, please open the pr again and i'll  describe all the defects in detail.

**Comment by felixmosh** [comment]
When v2 will be published / ready?
I would like to update the current version, can you specify the defects?

**Comment by maxmarinich** [comment]
Hi, @felixmosh! Thanks very much for the patience. New version and live [demo](https://maxmarinich.github.io/react-alice-carousel/static/) are available.
I guess the best idea is create a smart and an expected behavior for RTL support in `v2`.  Becouse 

I see it something like this. If we specify `rtl` the gallery automatically will reverse items (likeness `flex-direction` property). All gallery elements like arrows or dots also should adapt. We should consider the consistency of all aspects of the behavior like resize, the switching or combination between animations  and of course props updates.

I have a vision for implementing this feature.  Hope to include it in upcoming releases. Of course, help and any input are welcome.

**Comment by felixmosh** [comment]
@maxmarinich, thanx for updating.

What is the difference between my implementation and what you are planning to implement?
Pay attention to keyboard nav, it should be flipped as well.

**Comment by felixmosh** [comment]
Any updates regarding RTL support in v2?

**Comment by maxmarinich** [comment]
Hi, @felixmosh! Hope soon, work in progress.

**Comment by martdavidson** [comment]
Excited to see what you come up with @maxmarinich - we're moving to full RTL support and this carousel is the last piece of the puzzle.

**Pull request closed without merging**
